### ISSUE TITLE
Error in console and every player joined is jailed

### ISSUE THREAD

**Issue by kabluinc** [hoyinm14mc/Jail#10]
Error in console: Notice: Undefined index: jailed in C:\Users\Gamer27832 server\Desktop\New folder (10)\plugins\Jail-master\src\hoyinm14mc\jail\Jail.php on line 302

**Comment by gordonmhy** [comment]
Thanks! I'll check it

**Comment by gordonmhy** [comment]
Btw which build were you using when you have noticed this bug?

**Comment by gordonmhy** [comment]
@kabluinc
