### ISSUE TITLE
There is a bug in this last update

### ISSUE THREAD

**Issue by PocketDroidYT** [hoyinm14mc/Jail#14]
In this last update I can not trap anyone in the cage, when I give the / jail command the following message appears "an unknown error occurred while trying to perform this command"

**Comment by gordonmhy** [comment]
I'll check it

**Comment by gordonmhy** [comment]
@PocketDroidYT
Have you entered correct (valid) parameters in the command?
You can try reinstalling the plugin and test:
1. Run the following command in the console: /jail <playername> <EXISTING_jail> 1
2. Run the following command in-game: /jail <playername> <EXISTING_jail> 1
If one of them don't work, please send me the linked economic plugin's name to me, and the version of Jail that your using.  Thanks for using Jail!
(I don't have the error showing while executing the command on the console.  Maybe try reinstalling the plugin and test it again?)
