### ISSUE TITLE
Error on: Jail UUID

### ISSUE THREAD

**Issue by ghost** [hoyinm14mc/Jail#16]
How i can de-activate this feature?

Is buggy. Crash my server.

Bug not fixed: Fixed non-jailed players get kicked upon second join and crash server

**Comment by gordonmhy** [comment]
Thanks for reporting the bug.  I'll look into it.

**Comment by Starflux** [comment]
just tested Jail vAlpha0.3.4 and UUID now works with NON OP users as expected.

noticed the player structure has changed:

troll923:
  jailed: true
  gamemode: 1
  voteForJail:
    votes: 0
    votedBy: []
  uuid: 75404484-b72b-3295-8d4c-794dea73a0a4
  jail: jail1
  seconds: -79
  reason: no reason
  inventory: []

Thankyou for taking the time to look at this.

Regards
Star
