### ISSUE TITLE
/votejail and /unjail and more NOT WORK

### ISSUE THREAD

**Issue by ghost** [hoyinm14mc/Jail#18]
![image](https://cloud.githubusercontent.com/assets/13573011/23097813/763c2d86-f647-11e6-9a82-fbea3ceb7239.png)

If i'm used /votejail and /unjail NOT WORK.

Message.yml not work for me, and i have this config:

"allow-chat: true
allow-command: false
allow-block-break: false
allow-block-place: false
#If false, restricts player's VECTOR3 movement, not whole POSITION
allow-movement: true
allow-attack: false
disable-damage: true"

Not work and "allow-chat", but is true.

Edit: For /votejail and /unjail : Player have name "xDenys15" ,but in config is "xdenys15"

Is one difference. You can fix that?

**Comment by hoyinm14mc** [comment]
disable-damage field you've entered a string.  It should be true instead of true"

**Comment by gordonmhy** [comment]
Player names are all turned to lowercase.

**Comment by gordonmhy** [comment]
All problems are probably caused by the incomplete conversion of players' names to lowercases.  I'll fix all of them as soon as possible!
