### ISSUE TITLE
Jailed players can do everything thats restricted

### ISSUE THREAD

**Issue by kabluinc** [hoyinm14mc/Jail#22]
Only movement is restricted. Players can still chat, run commands, break/place blocks even though its set to false in command.

Using latest version from github

**Comment by gordonmhy** [comment]
Okay I'll test it and look into it.

**Comment by gordonmhy** [comment]
Did you set a mine for the jail?

**Comment by gordonmhy** [comment]
By the way I don't find problems of restricting prisoners to run commands.. It works perfectly for me.  But there is a permission node controlling this thing ('jail.override.restrictions').  Did you give this permission to some players?

**Comment by kabluinc** [comment]
oooh very sorry. I only tested the current version on an opped player. Works with non-ops or players without the permission. Thanks for your help
