### ISSUE TITLE
offline timer is lagging

### ISSUE THREAD

**Issue by dries-c** [hoyinm14mc/Jail#25]
why you dont make a until store
so the server dont need to count

**Comment by gordonmhy** [comment]
This is convenient for the output of timerGUI of prisoners :)

**Comment by dries-c** [comment]
but bansystem only saves untils and if a players joins
the countdown will be given

**Comment by gordonmhy** [comment]
https://github.com/hoyinm14mc/Jail/commit/52b38db42f1feb281528212cd16d3b39b0b0f68d
Check out this commit.  It probably fixes the problem that you mentioned.
