### ISSUE TITLE
upgrade Alpha8

### ISSUE THREAD

**Issue by teracube** [hoyinm14mc/Jail#42]
hi,
please upgrade Alpha8
thanks

**Comment by gordonmhy** [comment]
@teracube Sorry about that..  I'll update it when PocketMine releases 3.0.0 (Not Alpha nor Beta)
https://twitter.com/hoyinm14mc/status/911532858463752192
<img width="616" alt="screen shot 2017-09-23 at 6 11 21 pm" src="https://user-images.githubusercontent.com/9572632/30772259-a68d759c-a08a-11e7-91b9-f9b8218e4980.png">
