### ISSUE TITLE
Stay Updated Stay New...

### ISSUE THREAD

**Issue by brokiem** [hoyinm14mc/Jail#53]
Is this project still continuing? @gordonmhy

**Comment by brokiem** [comment]
Error: 

Error: Argument 2 passed to pocketmine\inventory\BaseInventory::setItem() must be an instance of pocketmine\item\Item, string given, called in phar:///root/kawaismp/survival3/PocketMine-MP.phar/src/pocketmine/inventory/BaseInventory.php on line 134
File: src/pocketmine/inventory/BaseInventory
Line: 157
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: Jail v1.3.0

Code:
[148] 	 */
[149] 	public function dropContents(Level $level, Vector3 $position) : void{
[150] 		foreach($this->getContents() as $item){
[151] 			$level->dropItem($position, $item);
[152] 		}
[153] 
[154] 		$this->clearAll();
[155] 	}
[156] 
[157] 	public function setItem(int $index, Item $item, bool $send = true) : bool{
[158] 		if($item->isNull()){
[159] 			$item = ItemFactory::get(Item::AIR, 0, 0);
[160] 		}else{
[161] 			$item = clone $item;
[162] 		}
[163] 
[164] 		$oldItem = $this->getItem($index);
[165] 		if($this->eventProcessor !== null){
[166] 			$newItem = $this->eventProcessor->onSlotChange($this, $index, $oldItem, $item);
[167] 			if($newItem === null){

Backtrace:
#0 src/pocketmine/inventory/BaseInventory(134): pocketmine\inventory\BaseInventory->setItem(integer 0, string[182] O:25:"pocketmine\item\ItemBlock":6:{s:10:".*.blockId";i:5;s:5:".*.id";i:5;s:7:"., boolean )
#1 plugins/Jail-master/src/hoyinm14mc/jail/Jail(525): pocketmine\inventory\BaseInventory->setContents(array[6])
#2 plugins/Jail-master/src/hoyinm14mc/jail/tasks/JailTimingTask(45): hoyinm14mc\jail\Jail->unjail(string[11] brokiemydog)
#3 src/pocketmine/scheduler/TaskHandler(134): hoyinm14mc\jail\tasks\JailTimingTask->onRun(integer 1461)
#4 src/pocketmine/scheduler/TaskScheduler(176): pocketmine\scheduler\TaskHandler->run(integer 1461)
#5 src/pocketmine/plugin/PluginManager(643): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 1461)
#6 src/pocketmine/Server(2380): pocketmine\plugin\PluginManager->tickSchedulers(integer 1461)
#7 src/pocketmine/Server(2143): pocketmine\Server->tick()
#8 src/pocketmine/Server(1990): pocketmine\Server->tickProcessor()
#9 src/pocketmine/Server(1584): pocketmine\Server->start()
#10 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[25] /root/kawaismp/survival3/, string[33] /root/kawaismp/survival3/plugins/)
#11 src/pocketmine/PocketMine(295): pocketmine\server()
#12 (11): require(string[80] phar:///root/kawaismp/survival3/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.12.3 [Protocol 390]
Git commit: e87e974323aaf5c16916def23fc01234913d3aa1
uname -a: Linux Shosting 5.3.0-1023-aws #25~18.04.1-Ubuntu SMP Fri Jun 5 15:18:30 UTC 2020 x86_64
PHP Version: 7.3.14
Zend version: 3.3.14
OS : Linux, linux

Loaded plugins:
ChestShop 5.0.1 by  for API(s) 3.11.1
RedstoneCircuit 2.0.0 by tedo0627 for API(s) 3.6.0
ScoreHud 5.2.0 by JackMD for API(s) 3.0.0
VanishV2 1.7 by superbobby for API(s) 3.0.0
MultiWorld 1.5.1 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 3.0.0
FormAPI 1.3.0 by jojoe77777 for API(s) 3.2.0
BlocksConverter 2.0.3 by matcracker for API(s) 3.0.0
EconomyAPI 5.7.2 by onebone for API(s) 3.0.0
Slapper 1.5.2 by jojoe77777 for API(s) 3.9.0
KeepInventory 1.0 by KhoaGamingPro for API(s) 3.0.0
EnchantUI 0.5 by UnknownOre for API(s) 3.0.0
Fireworks 0.0.3 by  for API(s) 3.9.0
TempBanUI 2.3 by SonsaYT for API(s) 3.0.0, 4.0.0
DevTools 1.13.5 by PocketMine Team for API(s) 3.4.0
InvSee 1.0.0 by BlockHorizons for API(s) 3.9.0
NoDecay 0.0.1 by RedCraftPE for API(s) 3.0.0
StarterKit 1.0.1 by TheNote for API(s) 3.9.0
SlapperRotation 1.2.1 by jojoe77777 for API(s) 3.0.0
SellAll 1.3.0 by AndreasHGK for API(s) 3.0.0
AlwaysSpawn 2.2.4 by Philip Shilling for API(s) 3.0.0
WorldLoader 1.0.0 by JackMD for API(s) 3.0.0
Worlds 3.0.0 by survanetwork for API(s) 3.0.0
PlayerVaults 3.2.1 by  for API(s) 3.0.0
Texter 3.4.7 by yuko_fuyutsuki, mfmfnek0, onebone, ogiwara, Shootsta_ERU0531, Toganon, ShadowArt, Marron0421, No4NaMe, SuperYYT, SuperAdam47, minijaham for API(s) 3.10.0
MSpawns 2.2 by EvolSoft for API(s) 3.0.0
KillRewards 1.2.0 by Dim9999 for API(s) 3.0.0
PurePerms 1.4.3 by 64FF00 & ProjectInfinity for API(s) 3.0.0
BanItem 2.3.3 by LDX for API(s) 3.0.0
RestrictedSkins 1.5.0 by SalmonDE for API(s) 3.0.0
BlockSniper 3.2.3 by BlockHorizons, Sandertv (@Sandertv), Chris-Prime (@PrimusLV) for API(s) 3.2.0
AutoClearLagg 3.0.1 by Twisted for API(s) 3.0.0
WorldPlayerCount 2.0-beta by xXKHaLeD098Xx for API(s) 3.0.0
SAC 3.6.6 by DarkWav for API(s) 3.0.0
BetterVoting 1.7 by Twisted for API(s) 3.0.0
ModePengintai 3.0.1 by MulqiGaming64 for API(s) 3.0.0
BuilderTools 1.2.0-beta2 by CzechPMDevs, VixikCZ for API(s) 3.0.0
PortalsPE 2.0.0 by luca28pet for API(s) 3.0.0
AuctionHouse 1.1.0 by Shock95x for API(s) 3.0.0
CustomShopUI 4.0.5 by SaltyPixelDevz for API(s) 3.0.0
PureChat 1.4.11 by 64FF00 for API(s) 3.0.0
McMMO 1.0.0 by Akmal for API(s) 3.0.0
TeaSpoon 1.2.0 by CortexPE for API(s) 3.9.0
RedEssentials 1.0.0 by RedCraftPE, EventfulDeer48, ItsMax123 for API(s) 3.0.0, 4.0.0
Hats 1 by  for API(s) 3.12
essentialsTP 1.2.2 by  for API(s) 3.0.0
WorldProtect 2.3.8 by aliuly for API(s) 3.0.0
TransferAPI 1.0 by Yesdog, Xernium, TobiasDev for API(s) 3.0.0
SeeDevice 1.1.0 by Palente for API(s) 3.11
ShopOnSign 1.0.0 by onebone, brokiem for API(s) 3.0.0-ALPHA12, 3.0.0, 4.0.0
NanoWild 1.0.0 by ItsGabry for API(s) 3.0.0
RepairRenameUI 1.0.2 by Array for API(s) 3.0.0
Event 2 by pmmp for API(s) 3.0.0
BetterNick 1.0.0 by HimmelKreis4865 for API(s) 3.0.0
EasyHeightLimit 1.0.0 by ElementalMinecraftGaming for API(s) 3.11.4
Jail 1.3.0 by hoyinm14mc for API(s) 3.12.0
RankInfoUI_By_NaufalBlaze 2 by NaufalBlazeYT for API(s) 3.0.0, 4.0.0
InfoUI 2 by Ameer4Real for API(s) 3.0.0

**Comment by gordonmhy** [comment]
I might rewrite the whole plugin and push an update by the end of this summer.  It may not happen because I have been inactive for quite a while and I have to catch up with how PocketMine is going in order to successfully update it.
